web-to-kafka:
  hello-message: hello from web to kafka

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

#kafka-config:
#  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
#  schema-registry-url-key: schema.registry.url
#  schema-registry-url: http://localhost:8081
#  topic-name: user-topic
#  topic-names-to-create:
#    - user-topic
#  num-of-partitions: 3
#  replication-factor: 3

kafka-config:
  bootstrap-servers: localhost:9092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: user-topic
  topic-names-to-create:
    - user-topic
  num-of-partitions: 3
  replication-factor: 1